[package]
name = "toy_browser_engine"
version = "0.1.0"
authors = ["Ted Price <ted.price@centro.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
